secrets:
  traefik_cf-dns-api-token:
  # The DNS provider's DNS API token.
    external: true
  traefik_cf-zone-api-token:
  # The DNS provider's zone API token.
    external: true
services:
  1generator:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.1generator_secure.tls.certresolver=default
  adminer:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.adminer_secure.middlewares=auth
      - traefik.http.routers.adminer_secure.tls.certresolver=default
  creal:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.creal_secure.tls.certresolver=default
    environment:
      HOST: 0.0.0.0
    image: dargmuesli/creal:0.44.18@sha256:92f604ed0bd23b823b4785e4a065aa6fd7fb978f807301916d3dcdd301224b27
    user: (( prune ))
    volumes: (( prune ))
  creal-postgraphile:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.creal-postgraphile_secure.tls.certresolver=default
  creal_strapi:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.creal_strapi_secure.tls.certresolver=default
    image: dargmuesli/creal_strapi:2.4.5@sha256:8e901c1c3d97aefa13f0eb06dad6a4d5bf639c7e3be321b05d5fbe58efde8ca2
    volumes:
    - creal_strapi_data:/app/public/
  hedgedoc:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.hedgedoc_secure.tls.certresolver=default
  jonas-thelemann:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.jonas-thelemann_secure.tls.certresolver=default
      - traefik.http.services.jonas-thelemann.loadbalancer.server.port=80
    image: dargmuesli/jonas-thelemann:4.11.5@sha256:df14895db7a54f39cf4a4dc92e1cfbdd22b1b0deaa8dcf7c0cff6e0a72d381ac
    user: (( prune ))
    volumes: (( prune ))
  nextcloud_nginx:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.nextcloud_nginx_secure.tls.certresolver=default
      - traefik.http.routers.nextcloud_nginx_secure_calendar.tls.certresolver=default
      - traefik.http.routers.nextcloud_nginx_secure_contacts.tls.certresolver=default
  node-binance-trader:
  # You cannot access the trader via a web interface.
    command: yarn run trader
    image: herve76/node-binance-trader:testing@sha256:c74836f84f85e03dc0b0e3f3bde43e02e1cdb98fb204ed60086206b1f26db07c
    volumes:
    - ./secrets/node-binance-trader/secrets.env:/srv/app/.env:ro
  portainer:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.portainer_secure.tls.certresolver=default
  postgres_backup:
  # Backup service for `postgres`.
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres-backup_db
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER_FILE: /run/secrets/postgres_user
    image: prodrigestivill/postgres-backup-local:14-alpine@sha256:863b68e3c1ccc25fae482aa684f8acc633d83fbbc2bb9def6f62666d81f0efd8
    secrets:
    - postgres-backup_db
    - postgres_password
    - postgres_user
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    - ../production/backups/postgres/:/backups/
  thelounge:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.thelounge_secure.tls.certresolver=default
  traefik:
    command:
    - (( prepend ))
    - --certificatesResolvers.default.acme.email=${STACK_ACME_EMAIL}
    - --certificatesResolvers.default.acme.storage=/etc/traefik/acme/acme.json
    - --certificatesResolvers.default.acme.dnsChallenge.provider=${STACK_ACME_PROVIDER}
    - --pilot.token=${TRAEFIK_PILOT_TOKEN}
    deploy:
      labels:
      - (( append ))
      - traefik.http.middlewares.auth.basicauth.users=${STACK_AUTH_BASIC}
      - traefik.http.routers.traefik_secure.middlewares=auth
      - traefik.http.routers.traefik_secure.tls.certresolver=default
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/traefik_cf-dns-api-token
      CF_ZONE_API_TOKEN_FILE: /run/secrets/traefik_cf-zone-api-token
    secrets:
    - traefik_cf-dns-api-token
    - traefik_cf-zone-api-token
  traefik_certs-dumper:
  # See [DargStack template: certificates](https://github.com/dargmuesli/dargstack_template/#certificates).
    command:
    - file
    - --clean=false
    - --crt-name="$STACK_DOMAIN"
    - --dest=/etc/traefik/acme/
    - --key-name="$STACK_DOMAIN"
    - --source=/etc/traefik/acme/acme.json
    - --version=v2
    - --watch
    environment:
      STACK_DOMAIN: ${STACK_DOMAIN}
    image: ldez/traefik-certs-dumper:v2.8.1@sha256:2734462fc8290feab0e34a00d5f3e4992ba74f8e3712d74efff7ae703d0e7e87
    volumes:
    - acme_data:/etc/traefik/acme/
  trapparty:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.trapparty_secure.tls.certresolver=default
    environment:
      HOST: 0.0.0.0
    image: dargmuesli/trapparty:2.6.19@sha256:df017ae2f1dd03c37cbc68cb3a830aa6689e7a0d7603499f8ef46221abdda8f5
    user: (( prune ))
    volumes: (( prune ))
  trapparty-postgraphile:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.trapparty-postgraphile_secure.tls.certresolver=default
version: "3.7"
volumes:
  acme_data:
  # The reverse proxy's certificate data.
    {}
  creal_strapi_data:
  # The DJ website's CMS data.
    {}
