secrets:
  traefik_cf-dns-api-token:
  # The DNS provider's DNS API token.
    external: true
  traefik_cf-zone-api-token:
  # The DNS provider's zone API token.
    external: true
services:
  1generator:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.1generator_secure.tls.certresolver=default
  adminer:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.adminer_secure.middlewares=auth
      - traefik.http.routers.adminer_secure.tls.certresolver=default
  creal:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.creal_secure.tls.certresolver=default
    image: dargmuesli/creal:0.31.3@sha256:e867fac3322c54979f28df74a0bf224076bfe810257c745734e1a504e5f9991d
    user: (( prune ))
    volumes: (( prune ))
  creal-postgraphile:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.creal-postgraphile_secure.tls.certresolver=default
  creal_strapi:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.creal_strapi_secure.tls.certresolver=default
    image: dargmuesli/creal_strapi:1.2.20@sha256:de1904942a5c4237c3a06be133f9cee19302e0a835843ce7869045ba26b76429
    volumes:
    - creal_strapi_data:/srv/app/
  hedgedoc:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.hedgedoc_secure.tls.certresolver=default
  jonas-thelemann:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.jonas-thelemann_secure.tls.certresolver=default
      - traefik.http.services.jonas-thelemann.loadbalancer.server.port=80
    image: dargmuesli/jonas-thelemann:4.7.1@sha256:2fc169f4d166761916fd4e28339fc8ca0ae0b3e75575b9346b681777a0c9e881
    volumes: (( prune ))
  jonas-thelemann_v3_nginx:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.jonas-thelemann_v3_nginx_secure.tls.certresolver=default
      - traefik.http.routers.jonas-thelemann_v3_nginx_secure_tools.middlewares=auth
      - traefik.http.routers.jonas-thelemann_v3_nginx_secure_tools.tls.certresolver=default
    volumes:
    - (( replace ))
    - ./configurations/jonas-thelemann_v3_nginx/nginx.conf:/etc/nginx/nginx.conf
    - jonas-thelemann_v3_data:/var/www/jonas-thelemann/server/:ro
    - acme_data:/etc/ssl/certificates/
  nextcloud_nginx:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.nextcloud_nginx_secure.tls.certresolver=default
      - traefik.http.routers.nextcloud_nginx_secure_calendar.tls.certresolver=default
      - traefik.http.routers.nextcloud_nginx_secure_contacts.tls.certresolver=default
  node-binance-trader:
  # You cannot access the trader via a web interface.
    command: yarn run trader
    image: herve76/node-binance-trader:testing@sha256:b11ade4a017d06a4a6a89b539dd5399723a01165a0836f5fb6d0c7701394a634
    volumes:
    - ./secrets/node-binance-trader/secrets.env:/srv/app/.env:ro
  portainer:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.portainer_secure.tls.certresolver=default
  postgres_backup:
  # Backup service for `postgres`.
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres-backup_db
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER_FILE: /run/secrets/postgres_user
    image: prodrigestivill/postgres-backup-local:14-alpine@sha256:9fc3b9321a0a36ec21963d7388d3cfb57d11c5f6d07176a2fd1398cca08f1e70
    secrets:
    - postgres-backup_db
    - postgres_password
    - postgres_user
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    - ../production/backups/postgres/:/backups/
  randomwinpicker_nginx:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.randomwinpicker_nginx_secure.tls.certresolver=default
  thelounge:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.thelounge_secure.tls.certresolver=default
  traefik:
    command:
    - (( prepend ))
    - --certificatesResolvers.default.acme.email=${STACK_ACME_EMAIL}
    - --certificatesResolvers.default.acme.storage=/etc/traefik/acme/acme.json
    - --certificatesResolvers.default.acme.dnsChallenge.provider=${STACK_ACME_PROVIDER}
    - --pilot.token=${TRAEFIK_PILOT_TOKEN}
    deploy:
      labels:
      - (( append ))
      - traefik.http.middlewares.auth.basicauth.users=${STACK_AUTH_BASIC}
      - traefik.http.routers.traefik_secure.middlewares=auth
      - traefik.http.routers.traefik_secure.tls.certresolver=default
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/traefik_cf-dns-api-token
      CF_ZONE_API_TOKEN_FILE: /run/secrets/traefik_cf-zone-api-token
    secrets:
    - traefik_cf-dns-api-token
    - traefik_cf-zone-api-token
  traefik_certs-dumper:
  # See [DargStack template: certificates](https://github.com/dargmuesli/dargstack_template/#certificates).
    command:
    - file
    - --clean=false
    - --crt-name="$STACK_DOMAIN"
    - --dest=/etc/traefik/acme/
    - --key-name="$STACK_DOMAIN"
    - --source=/etc/traefik/acme/acme.json
    - --version=v2
    - --watch
    environment:
      STACK_DOMAIN: ${STACK_DOMAIN}
    image: ldez/traefik-certs-dumper:v2.7.4@sha256:a56e96221153e24301263e16de278657204e9c5aff5bf1be0d55575619fd42f0
    volumes:
    - acme_data:/etc/traefik/acme/
  trapparty:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.trapparty_secure.tls.certresolver=default
    image: dargmuesli/trapparty:1.12.10@sha256:f973845a5eb36281c404efe2a2f8fbb201af755c1d62eca75b1bce9604554047
    user: (( prune ))
    volumes: (( prune ))
  trapparty-postgraphile:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.trapparty-postgraphile_secure.tls.certresolver=default
version: "3.7"
volumes:
  acme_data:
  # The reverse proxy's certificate data.
    {}
  creal_strapi_data:
  # The DJ website's CMS data.
    {}
