secrets:
  postgres-backup_db:
  # The database backup service's database name.
    external: true
  traefik_cf-dns-api-token:
  # The DNS provider's DNS API token.
    external: true
  traefik_cf-zone-api-token:
  # The DNS provider's zone API token.
    external: true
services:
  1generator:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.1generator_secure.tls.certresolver=default
  adminer:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.adminer_secure.middlewares=auth
      - traefik.http.routers.adminer_secure.tls.certresolver=default
  creal:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.creal_secure.tls.certresolver=default
    image: ghcr.io/dargmuesli/creal:1.8.5@sha256:9f47a710fec2ca6e3c176897b8cae75304ea122a255352277ef6bb6a65359551
    user: (( prune ))
    volumes: (( prune ))
  creal_postgraphile:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.creal_postgraphile_secure.tls.certresolver=default
  creal_strapi:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.creal_strapi_secure.tls.certresolver=default
    image: ghcr.io/dargmuesli/creal_strapi:2.5.18@sha256:974fa719a12466a11ccf72230dc5ebb7dad34c696b399aca45fb5f85594415df
    user: (( prune ))
    volumes:
    - (( prune ))
    - creal_strapi_data:/srv/app/public/
  hedgedoc:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.hedgedoc_secure.tls.certresolver=default
  jonas-thelemann: (( prune ))
    # deploy:
    #   labels:
    #   - (( append ))
    #   - traefik.http.routers.jonas-thelemann_secure.tls.certresolver=default
    #   - traefik.http.services.jonas-thelemann.loadbalancer.server.port=80
    # image: ghcr.io/dargmuesli/jonas-thelemann:5.12.7@sha256:7bee4c30be72647baf9ca61e5b2963e82d3ed1f0cb722bcd120da5f54b77ac2c
    # user: (( prune ))
    # volumes: (( prune ))
  minio: (( prune ))
  nextcloud_nginx:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.nextcloud_nginx_secure.tls.certresolver=default
      - traefik.http.routers.nextcloud_nginx_secure_calendar.tls.certresolver=default
      - traefik.http.routers.nextcloud_nginx_secure_contacts.tls.certresolver=default
  portainer:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.portainer_secure.tls.certresolver=default
  postgres_backup:
  # Backup service for `postgres`.
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres-backup_db
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER_FILE: /run/secrets/postgres_user
    image: prodrigestivill/postgres-backup-local:15-alpine@sha256:da879cc0012841820854bee1a71306b116cf2d0c85f25de342522f0b6f281a4e
    secrets:
    - postgres-backup_db
    - postgres_password
    - postgres_user
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    - ../production/backups/postgres/:/backups/
  thelounge:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.thelounge_secure.tls.certresolver=default
  traefik:
    command:
    - (( prepend ))
    - --certificatesResolvers.default.acme.email=${STACK_ACME_EMAIL}
    - --certificatesResolvers.default.acme.storage=/etc/traefik/acme/acme.json
    - --certificatesResolvers.default.acme.dnsChallenge.provider=${STACK_ACME_PROVIDER}
    - --pilot.token=${TRAEFIK_PILOT_TOKEN}
    deploy:
      labels:
      - (( append ))
      - traefik.http.middlewares.auth.basicauth.users=${STACK_AUTH_BASIC}
      - traefik.http.routers.traefik_secure.middlewares=auth
      - traefik.http.routers.traefik_secure.tls.certresolver=default
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/traefik_cf-dns-api-token
      CF_ZONE_API_TOKEN_FILE: /run/secrets/traefik_cf-zone-api-token
    secrets:
    - traefik_cf-dns-api-token
    - traefik_cf-zone-api-token
  traefik_certs-dumper:
  # You cannot access the reverse proxy's certificate helper directly.
    command:
    - file
    - --clean=false
    - --crt-name="$STACK_DOMAIN"
    - --dest=/etc/traefik/acme/
    - --key-name="$STACK_DOMAIN"
    - --source=/etc/traefik/acme/acme.json
    - --version=v2
    - --watch
    environment:
      STACK_DOMAIN: ${STACK_DOMAIN}
    image: ldez/traefik-certs-dumper:v2.8.1@sha256:2734462fc8290feab0e34a00d5f3e4992ba74f8e3712d74efff7ae703d0e7e87
    volumes:
    - acme_data:/etc/traefik/acme/
  trapparty:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.trapparty_secure.tls.certresolver=default
    image: ghcr.io/dargmuesli/trapparty:3.10.6@sha256:70829edc60b10e406bf254e160a7392429350e82e1eb8f7349e3622d49318817
    user: (( prune ))
    volumes: (( prune ))
  trapparty_postgraphile:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.trapparty_postgraphile_secure.tls.certresolver=default
version: "3.7"
volumes:
  acme_data:
  # The reverse proxy's certificate data.
    {}
  creal_strapi_data:
  # The DJ website's CMS data.
    {}
  minio_data: (( prune ))
