secrets:
  traefik_cf-dns-api-token:
  # The DNS provider's DNS API token.
    external: true
  traefik_cf-zone-api-token:
  # The DNS provider's zone API token.
    external: true
services:
  1generator:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.1generator_secure.tls.certresolver=default
  adminer:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.adminer_secure.middlewares=auth
      - traefik.http.routers.adminer_secure.tls.certresolver=default
  creal:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.creal_secure.tls.certresolver=default
    image: dargmuesli/creal:0.22.2@sha256:83b2d623f567a79b1618e24d45eef8e04a26f62b3fab5df4c74fb362ce909291
    user: (( prune ))
    volumes: (( prune ))
  creal_strapi:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.creal_strapi_secure.tls.certresolver=default
    image: dargmuesli/creal_strapi:1.2.7@sha256:b97f8c3cb5b3334f5cf7212deb5e2b978bce5abaf9f40ca95d4322c620d8e011
    volumes:
    - creal_strapi_data:/srv/app/
  hedgedoc:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.hedgedoc_secure.tls.certresolver=default
  jonas-thelemann:
    image: dargmuesli/jonas-thelemann:3.5.5@sha256:d40aa1c76abebee7c2fb1fcd0ccf48aedea4eee14825859924d47cf746339923
    user: (( prune ))
    volumes:
    - (( replace ))
    - ./secrets/jonas-thelemann/jonas-thelemann.env:/var/www/jonas-thelemann/credentials/jonas-thelemann.env:ro
    - jonas-thelemann_data:/var/www/jonas-thelemann/server/
    - acme_data:/etc/ssl/certificates/
  jonas-thelemann_nginx:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.jonas-thelemann_nginx_secure.tls.certresolver=default
      - traefik.http.routers.jonas-thelemann_nginx_secure_tools.middlewares=auth
      - traefik.http.routers.jonas-thelemann_nginx_secure_tools.tls.certresolver=default
    volumes:
    - (( replace ))
    - ./configuration/jonas-thelemann_nginx/nginx.conf:/etc/nginx/nginx.conf
    - jonas-thelemann_data:/var/www/jonas-thelemann/server/:ro
    - acme_data:/etc/ssl/certificates/
  nextcloud_nginx:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.nextcloud_nginx_secure.tls.certresolver=default
      - traefik.http.routers.nextcloud_nginx_secure_calendar.tls.certresolver=default
      - traefik.http.routers.nextcloud_nginx_secure_contacts.tls.certresolver=default
  portainer:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.portainer_secure.tls.certresolver=default
  postgres_backup:
  # Backup service for `postgres`.
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres-backup_db
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER_FILE: /run/secrets/postgres_user
    image: prodrigestivill/postgres-backup-local:12-alpine@sha256:e81310431a1ee259dc30ee683f840d3247de2df9dbf608e518673fb69a143230
    secrets:
    - postgres-backup_db
    - postgres_password
    - postgres_user
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    - ../production/backups/postgres/:/backups/
  randomwinpicker_nginx:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.randomwinpicker_nginx_secure.tls.certresolver=default
  thelounge:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.thelounge_secure.tls.certresolver=default
  traefik:
    command:
    - (( prepend ))
    - --certificatesResolvers.default.acme.email=${STACK_ACME_EMAIL}
    - --certificatesResolvers.default.acme.storage=/etc/traefik/acme/acme.json
    - --certificatesResolvers.default.acme.dnsChallenge.provider=${STACK_ACME_PROVIDER}
    deploy:
      labels:
      - (( append ))
      - traefik.http.middlewares.auth.basicauth.users=${STACK_AUTH_BASIC}
      - traefik.http.routers.traefik_secure.middlewares=auth
      - traefik.http.routers.traefik_secure.tls.certresolver=default
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/traefik_cf-dns-api-token
      CF_ZONE_API_TOKEN_FILE: /run/secrets/traefik_cf-zone-api-token
    secrets:
    - traefik_cf-dns-api-token
    - traefik_cf-zone-api-token
  traefik_certs-dumper:
  # See [DargStack template: certificates](https://github.com/dargmuesli/dargstack_template/#certificates).
    command:
    - file
    - --clean=false
    - --crt-name="$STACK_DOMAIN"
    - --dest=/etc/traefik/acme/
    - --key-name="$STACK_DOMAIN"
    - --source=/etc/traefik/acme/acme.json
    - --version=v2
    - --watch
    environment:
      STACK_DOMAIN: ${STACK_DOMAIN}
    image: ldez/traefik-certs-dumper:v2.7.4@sha256:a56e96221153e24301263e16de278657204e9c5aff5bf1be0d55575619fd42f0
    volumes:
    - acme_data:/etc/traefik/acme/
  trapparty:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.trapparty_secure.tls.certresolver=default
    image: dargmuesli/trapparty:1.10.2@sha256:b0b5d55caf556caf2c7ebb2466dc985ae57d52d8c2c566734904ba849bb28c96
    user: (( prune ))
    volumes: (( prune ))
  trapparty-postgraphile:
    deploy:
      labels:
      - (( append ))
      - traefik.http.routers.trapparty-postgraphile_secure.tls.certresolver=default
version: "3.7"
volumes:
  acme_data:
  # The reverse proxy's certificate data.
    {}
  creal_strapi_data:
  # The DJ website's CMS data.
    {}
  jonas-thelemann_data:
  # The main project's data.
    {}
