services:
  1generator:
    deploy:
      labels:
        - (( append ))
        - traefik.http.routers.1generator-secure.middlewares=cloudflarewarp
        - traefik.http.routers.1generator-secure.tls.certresolver=default
