services:
  creal-strapi:
    deploy:
      labels:
        - (( append ))
        - traefik.http.routers.creal-strapi-secure.middlewares=cloudflarewarp
        - traefik.http.routers.creal-strapi-secure.tls.certresolver=default
      update_config:
        order: stop-first
    image: ghcr.io/dargmuesli/creal-strapi:5.0.0
    volumes:
      - creal-strapi-data:/srv/app/public/
