secrets:
  postgres-backup-db:
    # The database backup service's database name.
    external: true
services:
  postgres:
    deploy:
      update_config:
        order: stop-first
  postgres-backup:
    # Backup service for `postgres`.
    deploy:
      labels:
        - dargstack.profiles=backup
      update_config:
        order: stop-first
    environment:
      POSTGRES_DB_FILE: /run/secrets/postgres-backup-db
      POSTGRES_HOST: postgres
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres-password
      POSTGRES_USER_FILE: /run/secrets/postgres-user
    image: prodrigestivill/postgres-backup-local:18-alpine
    secrets:
      - postgres-backup-db
      - postgres-password
      - postgres-user
    volumes:
      - postgres-data:/var/lib/postgresql/
      - ../backups/postgres/:/backups/
