#!/bin/sh

ln -f /etc/traefik/acme/certs/${1}.crt /etc/traefik/acme/${1%.*}.crt
ln -f /etc/traefik/acme/private/${1}.key /etc/traefik/acme/${1%.*}.key

ln -f /etc/traefik/acme/${1%.*}.crt /etc/traefik/acme/randomwinpicker.crt
ln -f /etc/traefik/acme/${1%.*}.key /etc/traefik/acme/randomwinpicker.key
