services:
  jobber:
    deploy:
      update_config:
        order: start-first
    environment:
      SENTRY_CRONS: ${SENTRY_CRONS}
    volumes:
      - (( append ))
      - ./configurations/sinks:/srv/sinks:ro
