services:
  creal:
    deploy:
      labels:
        - (( append ))
        - traefik.http.routers.creal-secure.middlewares=cloudflarewarp
        - traefik.http.routers.creal-secure.tls.certresolver=default
      update_config:
        order: start-first
    image: ghcr.io/dargmuesli/creal:6.2.0
    volumes: (( prune ))
