services:
  trapparty:
    deploy:
      labels:
        - (( append ))
        - traefik.http.routers.trapparty-secure.middlewares=cloudflarewarp
        - traefik.http.routers.trapparty-secure.tls.certresolver=default
      update_config:
        order: start-first
    image: ghcr.io/dargmuesli/trapparty:5.1.0
    volumes: (( prune ))
