services:
  trapparty:
    deploy:
      labels:
        - (( append ))
        - traefik.http.routers.trapparty-secure.middlewares=cloudflarewarp
        - traefik.http.routers.trapparty-secure.tls.certresolver=default
    image: ghcr.io/dargmuesli/trapparty:4.4.14
    volumes: (( prune ))
