services:
  adminer:
    deploy:
      labels:
        - (( append ))
        - traefik.http.routers.adminer-secure.middlewares=cloudflarewarp
        - traefik.http.routers.adminer-secure.tls.certresolver=default
